name: EnglishBrain
options:
  bundleIdPrefix: com.englishbrain
  deploymentTarget:
    iOS: "16.0"

packages:
  EnglishBrainAPI:
    path: ../sdk-swift

targets:
  EnglishBrain:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - EnglishBrain
    dependencies:
      - package: EnglishBrainAPI
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.englishbrain.EnglishBrain
        DEVELOPMENT_TEAM: ""
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
