//
// AttemptError.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AttemptError: Codable, JSONEncodable, Hashable {

    public enum Code: String, Codable, CaseIterable {
        case missingVerb = "missing-verb"
        case missingObject = "missing-object"
        case misplacedModifier = "misplaced-modifier"
        case tenseMismatch = "tense-mismatch"
        case articleError = "article-error"
        case prepositionError = "preposition-error"
        case auxiliaryError = "auxiliary-error"
    }
    public var code: Code
    public var message: String?
    public var details: [String: String]?

    public init(code: Code, message: String? = nil, details: [String: String]? = nil) {
        self.code = code
        self.message = message
        self.details = details
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case code
        case message
        case details
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(code, forKey: .code)
        try container.encodeIfPresent(message, forKey: .message)
        try container.encodeIfPresent(details, forKey: .details)
    }
}

