//
// CheckpointStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CheckpointStatus: Codable, JSONEncodable, Hashable {

    static let accuracyRule = NumericRule<Double>(minimum: 0, exclusiveMinimum: false, maximum: 1, exclusiveMaximum: false, multipleOf: nil)
    public var reached: Bool
    public var accuracy: Double?
    public var combosMax: Int?
    public var completedAt: Date?

    public init(reached: Bool, accuracy: Double? = nil, combosMax: Int? = nil, completedAt: Date? = nil) {
        self.reached = reached
        self.accuracy = accuracy
        self.combosMax = combosMax
        self.completedAt = completedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case reached
        case accuracy
        case combosMax
        case completedAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(reached, forKey: .reached)
        try container.encodeIfPresent(accuracy, forKey: .accuracy)
        try container.encodeIfPresent(combosMax, forKey: .combosMax)
        try container.encodeIfPresent(completedAt, forKey: .completedAt)
    }
}

