//
// DataExportRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct DataExportRequest: Codable, JSONEncodable, Hashable {

    public enum DeliveryChannel: String, Codable, CaseIterable {
        case email = "email"
        case inApp = "in-app"
    }
    /** Preferred channel for delivering the export link; defaults to email. */
    public var deliveryChannel: DeliveryChannel?

    public init(deliveryChannel: DeliveryChannel? = nil) {
        self.deliveryChannel = deliveryChannel
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case deliveryChannel
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(deliveryChannel, forKey: .deliveryChannel)
    }
}

