//
// DataDeletionResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct DataDeletionResponse: Codable, JSONEncodable, Hashable {

    public enum Status: String, Codable, CaseIterable {
        case scheduled = "scheduled"
        case inProgress = "in-progress"
        case completed = "completed"
    }
    public var requestId: UUID
    /** Target timestamp for physical deletion, typically within 30 days. */
    public var scheduledDeletionAt: Date
    public var status: Status

    public init(requestId: UUID, scheduledDeletionAt: Date, status: Status) {
        self.requestId = requestId
        self.scheduledDeletionAt = scheduledDeletionAt
        self.status = status
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case requestId
        case scheduledDeletionAt
        case status
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(requestId, forKey: .requestId)
        try container.encode(scheduledDeletionAt, forKey: .scheduledDeletionAt)
        try container.encode(status, forKey: .status)
    }
}

