//
// DataExportResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct DataExportResponse: Codable, JSONEncodable, Hashable {

    public enum Status: String, Codable, CaseIterable {
        case processing = "processing"
        case ready = "ready"
        case delivered = "delivered"
    }
    public var requestId: UUID
    /** Estimated time when the export archive will be available (≤ 72 hours). */
    public var estimatedReadyAt: Date
    public var status: Status

    public init(requestId: UUID, estimatedReadyAt: Date, status: Status) {
        self.requestId = requestId
        self.estimatedReadyAt = estimatedReadyAt
        self.status = status
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case requestId
        case estimatedReadyAt
        case status
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(requestId, forKey: .requestId)
        try container.encode(estimatedReadyAt, forKey: .estimatedReadyAt)
        try container.encode(status, forKey: .status)
    }
}

