//
// FrameSlot.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct FrameSlot: Codable, JSONEncodable, Hashable {

    public enum Role: String, Codable, CaseIterable {
        case s = "S"
        case v = "V"
        case o = "O"
        case m = "M"
    }
    public var role: Role
    public var label: String
    public var _optional: Bool

    public init(role: Role, label: String, _optional: Bool) {
        self.role = role
        self.label = label
        self._optional = _optional
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case role
        case label
        case _optional = "optional"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(role, forKey: .role)
        try container.encode(label, forKey: .label)
        try container.encode(_optional, forKey: ._optional)
    }
}

