//
// FrameToken.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct FrameToken: Codable, JSONEncodable, Hashable {

    public enum Role: String, Codable, CaseIterable {
        case s = "S"
        case v = "V"
        case o = "O"
        case m = "M"
    }
    public var tokenId: String
    public var display: String
    public var role: Role
    public var lemma: String?
    public var audioUrl: String?

    public init(tokenId: String, display: String, role: Role, lemma: String? = nil, audioUrl: String? = nil) {
        self.tokenId = tokenId
        self.display = display
        self.role = role
        self.lemma = lemma
        self.audioUrl = audioUrl
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case tokenId
        case display
        case role
        case lemma
        case audioUrl
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(tokenId, forKey: .tokenId)
        try container.encode(display, forKey: .display)
        try container.encode(role, forKey: .role)
        try container.encodeIfPresent(lemma, forKey: .lemma)
        try container.encodeIfPresent(audioUrl, forKey: .audioUrl)
    }
}

