//
// GetPatternConquests200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetPatternConquests200Response: Codable, JSONEncodable, Hashable {

    public var patterns: [PatternConquest]

    public init(patterns: [PatternConquest]) {
        self.patterns = patterns
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case patterns
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(patterns, forKey: .patterns)
    }
}

