//
// Hint.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Hint: Codable, JSONEncodable, Hashable {

    public enum ModelType: String, Codable, CaseIterable {
        case text = "text"
        case slotLabel = "slot-label"
        case highlight = "highlight"
        case reveal = "reveal"
    }
    public var order: Int
    public var type: ModelType
    public var content: String

    public init(order: Int, type: ModelType, content: String) {
        self.order = order
        self.type = type
        self.content = content
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case order
        case type
        case content
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(order, forKey: .order)
        try container.encode(type, forKey: .type)
        try container.encode(content, forKey: .content)
    }
}

