//
// HomeSummaryDailyGoal.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct HomeSummaryDailyGoal: Codable, JSONEncodable, Hashable {

    public enum Tier: String, Codable, CaseIterable {
        case basic = "basic"
        case intensive = "intensive"
    }
    public var sentences: Int
    public var minutes: Int
    /** Goal pacing tier determined by profile (basic 8–12분 / intensive 12–18분). */
    public var tier: Tier

    public init(sentences: Int, minutes: Int, tier: Tier) {
        self.sentences = sentences
        self.minutes = minutes
        self.tier = tier
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case sentences
        case minutes
        case tier
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(sentences, forKey: .sentences)
        try container.encode(minutes, forKey: .minutes)
        try container.encode(tier, forKey: .tier)
    }
}

