//
// HomeSummaryBrainTokens.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct HomeSummaryBrainTokens: Codable, JSONEncodable, Hashable {

    public var available: Int
    public var pending: Int

    public init(available: Int, pending: Int) {
        self.available = available
        self.pending = pending
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case available
        case pending
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(available, forKey: .available)
        try container.encode(pending, forKey: .pending)
    }
}

