//
// HomeSummaryStreak.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct HomeSummaryStreak: Codable, JSONEncodable, Hashable {

    public var current: Int
    public var longest: Int
    public var freezeEligible: Bool

    public init(current: Int, longest: Int, freezeEligible: Bool) {
        self.current = current
        self.longest = longest
        self.freezeEligible = freezeEligible
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case current
        case longest
        case freezeEligible
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(current, forKey: .current)
        try container.encode(longest, forKey: .longest)
        try container.encode(freezeEligible, forKey: .freezeEligible)
    }
}

