//
// HomeSummaryProgress.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct HomeSummaryProgress: Codable, JSONEncodable, Hashable {

    public var sentencesCompleted: Int
    public var minutesSpent: Int
    public var lastSessionAt: Date

    public init(sentencesCompleted: Int, minutesSpent: Int, lastSessionAt: Date) {
        self.sentencesCompleted = sentencesCompleted
        self.minutesSpent = minutesSpent
        self.lastSessionAt = lastSessionAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case sentencesCompleted
        case minutesSpent
        case lastSessionAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(sentencesCompleted, forKey: .sentencesCompleted)
        try container.encode(minutesSpent, forKey: .minutesSpent)
        try container.encode(lastSessionAt, forKey: .lastSessionAt)
    }
}

