//
// ItemFrame.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ItemFrame: Codable, JSONEncodable, Hashable {

    public var slots: [FrameSlot]

    public init(slots: [FrameSlot]) {
        self.slots = slots
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case slots
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(slots, forKey: .slots)
    }
}

