//
// ItemPrompt.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ItemPrompt: Codable, JSONEncodable, Hashable {

    public var ko: String
    public var enReference: String
    public var audioUrl: String?

    public init(ko: String, enReference: String, audioUrl: String? = nil) {
        self.ko = ko
        self.enReference = enReference
        self.audioUrl = audioUrl
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case ko
        case enReference
        case audioUrl
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(ko, forKey: .ko)
        try container.encode(enReference, forKey: .enReference)
        try container.encodeIfPresent(audioUrl, forKey: .audioUrl)
    }
}

