//
// LevelTestSubmission.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct LevelTestSubmission: Codable, JSONEncodable, Hashable {

    public var attempts: [LevelTestAttempt]
    public var startedAt: Date
    public var completedAt: Date

    public init(attempts: [LevelTestAttempt], startedAt: Date, completedAt: Date) {
        self.attempts = attempts
        self.startedAt = startedAt
        self.completedAt = completedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case attempts
        case startedAt
        case completedAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(attempts, forKey: .attempts)
        try container.encode(startedAt, forKey: .startedAt)
        try container.encode(completedAt, forKey: .completedAt)
    }
}

