//
// ListAttempts200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ListAttempts200Response: Codable, JSONEncodable, Hashable {

    public var attempts: [Attempt]

    public init(attempts: [Attempt]) {
        self.attempts = attempts
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case attempts
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(attempts, forKey: .attempts)
    }
}

