//
// ListReviews200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ListReviews200Response: Codable, JSONEncodable, Hashable {

    public var reviews: [ReviewPlan]

    public init(reviews: [ReviewPlan]) {
        self.reviews = reviews
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case reviews
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(reviews, forKey: .reviews)
    }
}

