//
// LiveActivityInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct LiveActivityInfo: Codable, JSONEncodable, Hashable {

    /** Indicates whether the current device is eligible for Live Activity. */
    public var supported: Bool
    /** True when a Live Activity session is currently running. */
    public var active: Bool
    public var activityId: UUID?
    public var lastUpdatedAt: Date?

    public init(supported: Bool, active: Bool, activityId: UUID? = nil, lastUpdatedAt: Date? = nil) {
        self.supported = supported
        self.active = active
        self.activityId = activityId
        self.lastUpdatedAt = lastUpdatedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case supported
        case active
        case activityId
        case lastUpdatedAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(supported, forKey: .supported)
        try container.encode(active, forKey: .active)
        try container.encodeIfPresent(activityId, forKey: .activityId)
        try container.encodeIfPresent(lastUpdatedAt, forKey: .lastUpdatedAt)
    }
}

