//
// LiveActivityRegisterRequestDeviceCapabilities.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct LiveActivityRegisterRequestDeviceCapabilities: Codable, JSONEncodable, Hashable {

    public var supportsLiveActivities: Bool?
    public var supportsDynamicIsland: Bool?

    public init(supportsLiveActivities: Bool? = nil, supportsDynamicIsland: Bool? = nil) {
        self.supportsLiveActivities = supportsLiveActivities
        self.supportsDynamicIsland = supportsDynamicIsland
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case supportsLiveActivities
        case supportsDynamicIsland
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(supportsLiveActivities, forKey: .supportsLiveActivities)
        try container.encodeIfPresent(supportsDynamicIsland, forKey: .supportsDynamicIsland)
    }
}

