//
// LiveActivityRegisterRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct LiveActivityRegisterRequest: Codable, JSONEncodable, Hashable {

    public var sessionId: UUID
    /** ActivityKit token used for direct updates. */
    public var activityToken: String
    /** APNs token used for Live Activity updates. */
    public var pushToken: String
    public var deviceCapabilities: LiveActivityRegisterRequestDeviceCapabilities?

    public init(sessionId: UUID, activityToken: String, pushToken: String, deviceCapabilities: LiveActivityRegisterRequestDeviceCapabilities? = nil) {
        self.sessionId = sessionId
        self.activityToken = activityToken
        self.pushToken = pushToken
        self.deviceCapabilities = deviceCapabilities
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case sessionId
        case activityToken
        case pushToken
        case deviceCapabilities
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(sessionId, forKey: .sessionId)
        try container.encode(activityToken, forKey: .activityToken)
        try container.encode(pushToken, forKey: .pushToken)
        try container.encodeIfPresent(deviceCapabilities, forKey: .deviceCapabilities)
    }
}

