//
// LiveActivityUpdateRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct LiveActivityUpdateRequest: Codable, JSONEncodable, Hashable {

    public enum Status: String, Codable, CaseIterable {
        case active = "active"
        case ended = "ended"
        case expired = "expired"
    }
    public var status: Status
    public var summary: SessionSummary?

    public init(status: Status, summary: SessionSummary? = nil) {
        self.status = status
        self.summary = summary
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case summary
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(status, forKey: .status)
        try container.encodeIfPresent(summary, forKey: .summary)
    }
}

