//
// NotificationOpenRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct NotificationOpenRequest: Codable, JSONEncodable, Hashable {

    public enum Surface: String, Codable, CaseIterable {
        case push = "push"
        case inApp = "in-app"
        case widget = "widget"
    }
    public enum ActionTaken: String, Codable, CaseIterable {
        case session = "session"
        case review = "review"
        case brainBurst = "brain-burst"
        case dismiss = "dismiss"
        case unknown = "unknown"
    }
    public var openedAt: Date
    public var surface: Surface?
    public var actionTaken: ActionTaken?

    public init(openedAt: Date, surface: Surface? = nil, actionTaken: ActionTaken? = nil) {
        self.openedAt = openedAt
        self.surface = surface
        self.actionTaken = actionTaken
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case openedAt
        case surface
        case actionTaken
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(openedAt, forKey: .openedAt)
        try container.encodeIfPresent(surface, forKey: .surface)
        try container.encodeIfPresent(actionTaken, forKey: .actionTaken)
    }
}

