//
// NotificationOpenResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct NotificationOpenResponse: Codable, JSONEncodable, Hashable {

    public enum Status: String, Codable, CaseIterable {
        case acknowledged = "acknowledged"
        case alreadyProcessed = "already-processed"
    }
    public var notificationId: String
    public var status: Status

    public init(notificationId: String, status: Status) {
        self.notificationId = notificationId
        self.status = status
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case notificationId
        case status
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(notificationId, forKey: .notificationId)
        try container.encode(status, forKey: .status)
    }
}

