//
// OfflineSyncRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct OfflineSyncRequest: Codable, JSONEncodable, Hashable {

    public var sessions: [Session]
    public var attempts: [Attempt]
    public var checkpoints: [Checkpoint]?
    public var pendingRewards: [PendingReward]?

    public init(sessions: [Session], attempts: [Attempt], checkpoints: [Checkpoint]? = nil, pendingRewards: [PendingReward]? = nil) {
        self.sessions = sessions
        self.attempts = attempts
        self.checkpoints = checkpoints
        self.pendingRewards = pendingRewards
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case sessions
        case attempts
        case checkpoints
        case pendingRewards
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(sessions, forKey: .sessions)
        try container.encode(attempts, forKey: .attempts)
        try container.encodeIfPresent(checkpoints, forKey: .checkpoints)
        try container.encodeIfPresent(pendingRewards, forKey: .pendingRewards)
    }
}

