//
// OfflineSyncResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct OfflineSyncResponse: Codable, JSONEncodable, Hashable {

    public var mergedSessions: [String]
    public var conflicts: [SyncConflict]
    public var pendingRewards: [PendingReward]?

    public init(mergedSessions: [String], conflicts: [SyncConflict], pendingRewards: [PendingReward]? = nil) {
        self.mergedSessions = mergedSessions
        self.conflicts = conflicts
        self.pendingRewards = pendingRewards
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case mergedSessions
        case conflicts
        case pendingRewards
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(mergedSessions, forKey: .mergedSessions)
        try container.encode(conflicts, forKey: .conflicts)
        try container.encodeIfPresent(pendingRewards, forKey: .pendingRewards)
    }
}

