//
// PatternConquest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PatternConquest: Codable, JSONEncodable, Hashable {

    public enum Trend: String, Codable, CaseIterable {
        case improving = "improving"
        case stable = "stable"
        case declining = "declining"
    }
    static let conquestRateRule = NumericRule<Double>(minimum: 0, exclusiveMinimum: false, maximum: 1, exclusiveMaximum: false, multipleOf: nil)
    static let severityRule = NumericRule<Int>(minimum: 1, exclusiveMinimum: false, maximum: 5, exclusiveMaximum: false, multipleOf: nil)
    static let hintRateRule = NumericRule<Double>(minimum: 0, exclusiveMinimum: false, maximum: 1, exclusiveMaximum: false, multipleOf: nil)
    static let firstTryRateRule = NumericRule<Double>(minimum: 0, exclusiveMinimum: false, maximum: 1, exclusiveMaximum: false, multipleOf: nil)
    public var patternId: String
    public var label: String
    public var conquestRate: Double
    public var severity: Int
    public var exposures: Int
    public var lastPracticedAt: Date
    public var trend: Trend
    public var hintRate: Double?
    public var firstTryRate: Double?

    public init(patternId: String, label: String, conquestRate: Double, severity: Int, exposures: Int, lastPracticedAt: Date, trend: Trend, hintRate: Double? = nil, firstTryRate: Double? = nil) {
        self.patternId = patternId
        self.label = label
        self.conquestRate = conquestRate
        self.severity = severity
        self.exposures = exposures
        self.lastPracticedAt = lastPracticedAt
        self.trend = trend
        self.hintRate = hintRate
        self.firstTryRate = firstTryRate
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case patternId
        case label
        case conquestRate
        case severity
        case exposures
        case lastPracticedAt
        case trend
        case hintRate
        case firstTryRate
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(patternId, forKey: .patternId)
        try container.encode(label, forKey: .label)
        try container.encode(conquestRate, forKey: .conquestRate)
        try container.encode(severity, forKey: .severity)
        try container.encode(exposures, forKey: .exposures)
        try container.encode(lastPracticedAt, forKey: .lastPracticedAt)
        try container.encode(trend, forKey: .trend)
        try container.encodeIfPresent(hintRate, forKey: .hintRate)
        try container.encodeIfPresent(firstTryRate, forKey: .firstTryRate)
    }
}

