//
// Placement.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Placement: Codable, JSONEncodable, Hashable {

    public enum Slot: String, Codable, CaseIterable {
        case s = "S"
        case v = "V"
        case o = "O"
        case m = "M"
    }
    public var slot: Slot
    public var tokenId: String

    public init(slot: Slot, tokenId: String) {
        self.slot = slot
        self.tokenId = tokenId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case slot
        case tokenId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(slot, forKey: .slot)
        try container.encode(tokenId, forKey: .tokenId)
    }
}

