//
// ReviewItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ReviewItem: Codable, JSONEncodable, Hashable {

    public var itemId: String
    public var prompt: ItemPrompt
    public var patternTags: [String]

    public init(itemId: String, prompt: ItemPrompt, patternTags: [String]) {
        self.itemId = itemId
        self.prompt = prompt
        self.patternTags = patternTags
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case itemId
        case prompt
        case patternTags
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(itemId, forKey: .itemId)
        try container.encode(prompt, forKey: .prompt)
        try container.encode(patternTags, forKey: .patternTags)
    }
}

