//
// ReviewSummary.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ReviewSummary: Codable, JSONEncodable, Hashable {

    static let accuracyRule = NumericRule<Double>(minimum: 0, exclusiveMinimum: false, maximum: 1, exclusiveMaximum: false, multipleOf: nil)
    public var accuracy: Double
    public var durationSeconds: Int
    public var completedAt: Date
    public var patternImpact: [PatternImpact]?

    public init(accuracy: Double, durationSeconds: Int, completedAt: Date, patternImpact: [PatternImpact]? = nil) {
        self.accuracy = accuracy
        self.durationSeconds = durationSeconds
        self.completedAt = completedAt
        self.patternImpact = patternImpact
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case accuracy
        case durationSeconds
        case completedAt
        case patternImpact
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(accuracy, forKey: .accuracy)
        try container.encode(durationSeconds, forKey: .durationSeconds)
        try container.encode(completedAt, forKey: .completedAt)
        try container.encodeIfPresent(patternImpact, forKey: .patternImpact)
    }
}

