//
// ReviewCreateRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ReviewCreateRequest: Codable, JSONEncodable, Hashable {

    public enum Trigger: String, Codable, CaseIterable {
        case auto = "auto"
        case user = "user"
        case notification = "notification"
    }
    public var trigger: Trigger
    public var patternId: String?
    public var targetSentences: Int? = 6

    public init(trigger: Trigger, patternId: String? = nil, targetSentences: Int? = 6) {
        self.trigger = trigger
        self.patternId = patternId
        self.targetSentences = targetSentences
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case trigger
        case patternId
        case targetSentences
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(trigger, forKey: .trigger)
        try container.encodeIfPresent(patternId, forKey: .patternId)
        try container.encodeIfPresent(targetSentences, forKey: .targetSentences)
    }
}

