//
// ScoringRules.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ScoringRules: Codable, JSONEncodable, Hashable {

    public var basePoints: Int
    public var comboBonus: Int
    public var hintPenalty: Int

    public init(basePoints: Int, comboBonus: Int, hintPenalty: Int) {
        self.basePoints = basePoints
        self.comboBonus = comboBonus
        self.hintPenalty = hintPenalty
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case basePoints
        case comboBonus
        case hintPenalty
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(basePoints, forKey: .basePoints)
        try container.encode(comboBonus, forKey: .comboBonus)
        try container.encode(hintPenalty, forKey: .hintPenalty)
    }
}

