//
// SessionCollection.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SessionCollection: Codable, JSONEncodable, Hashable {

    public var sessions: [Session]
    public var nextCursor: String

    public init(sessions: [Session], nextCursor: String) {
        self.sessions = sessions
        self.nextCursor = nextCursor
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case sessions
        case nextCursor
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(sessions, forKey: .sessions)
        try container.encode(nextCursor, forKey: .nextCursor)
    }
}

