//
// SessionUpdateRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SessionUpdateRequest: Codable, JSONEncodable, Hashable {

    public enum Status: String, Codable, CaseIterable {
        case completed = "completed"
        case abandoned = "abandoned"
    }
    public var status: Status
    public var summary: SessionSummary

    public init(status: Status, summary: SessionSummary) {
        self.status = status
        self.summary = summary
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case summary
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(status, forKey: .status)
        try container.encode(summary, forKey: .summary)
    }
}

