//
// SessionPhaseComboRules.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SessionPhaseComboRules: Codable, JSONEncodable, Hashable {

    public var base: Int
    public var bonusPerStreak: Int

    public init(base: Int, bonusPerStreak: Int) {
        self.base = base
        self.bonusPerStreak = bonusPerStreak
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case base
        case bonusPerStreak
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(base, forKey: .base)
        try container.encode(bonusPerStreak, forKey: .bonusPerStreak)
    }
}

