//
// TelemetryIngestResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TelemetryIngestResponse: Codable, JSONEncodable, Hashable {

    public var accepted: Int
    public var rejected: Int
    public var rejectionReasons: [String]?

    public init(accepted: Int, rejected: Int, rejectionReasons: [String]? = nil) {
        self.accepted = accepted
        self.rejected = rejected
        self.rejectionReasons = rejectionReasons
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case accepted
        case rejected
        case rejectionReasons
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(accepted, forKey: .accepted)
        try container.encode(rejected, forKey: .rejected)
        try container.encodeIfPresent(rejectionReasons, forKey: .rejectionReasons)
    }
}

