//
// TelemetryBatch.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TelemetryBatch: Codable, JSONEncodable, Hashable {

    public enum Source: String, Codable, CaseIterable {
        case client = "client"
        case offlineSync = "offline-sync"
    }
    public var events: [TelemetryEvent]
    public var source: Source?

    public init(events: [TelemetryEvent], source: Source? = nil) {
        self.events = events
        self.source = source
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case events
        case source
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(events, forKey: .events)
        try container.encodeIfPresent(source, forKey: .source)
    }
}

