//
// TutorialCompletionResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TutorialCompletionResponse: Codable, JSONEncodable, Hashable {

    public var tutorialId: String
    public var streakEligible: Bool
    public var personalizationUnlocked: Bool

    public init(tutorialId: String, streakEligible: Bool, personalizationUnlocked: Bool) {
        self.tutorialId = tutorialId
        self.streakEligible = streakEligible
        self.personalizationUnlocked = personalizationUnlocked
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case tutorialId
        case streakEligible
        case personalizationUnlocked
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(tutorialId, forKey: .tutorialId)
        try container.encode(streakEligible, forKey: .streakEligible)
        try container.encode(personalizationUnlocked, forKey: .personalizationUnlocked)
    }
}

