//
// TutorialCompletionRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TutorialCompletionRequest: Codable, JSONEncodable, Hashable {

    public var tutorialId: String
    public var completedAt: Date
    public var liveActivityId: UUID?

    public init(tutorialId: String, completedAt: Date, liveActivityId: UUID? = nil) {
        self.tutorialId = tutorialId
        self.completedAt = completedAt
        self.liveActivityId = liveActivityId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case tutorialId
        case completedAt
        case liveActivityId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(tutorialId, forKey: .tutorialId)
        try container.encode(completedAt, forKey: .completedAt)
        try container.encodeIfPresent(liveActivityId, forKey: .liveActivityId)
    }
}

