//
// UserProfileUpdate.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UserProfileUpdate: Codable, JSONEncodable, Hashable {

    public var displayName: String?
    public var timezone: String?
    public var locale: String?
    public var preferences: UserPreferencesUpdate?

    public init(displayName: String? = nil, timezone: String? = nil, locale: String? = nil, preferences: UserPreferencesUpdate? = nil) {
        self.displayName = displayName
        self.timezone = timezone
        self.locale = locale
        self.preferences = preferences
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case displayName
        case timezone
        case locale
        case preferences
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(displayName, forKey: .displayName)
        try container.encodeIfPresent(timezone, forKey: .timezone)
        try container.encodeIfPresent(locale, forKey: .locale)
        try container.encodeIfPresent(preferences, forKey: .preferences)
    }
}

