//
// UserFlags.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UserFlags: Codable, JSONEncodable, Hashable {

    public var levelTestCompleted: Bool
    public var tutorialCompleted: Bool
    public var personalizationReady: Bool
    public var dataDeletionScheduled: Bool? = false
    public var dataExportRequestedAt: Date?

    public init(levelTestCompleted: Bool, tutorialCompleted: Bool, personalizationReady: Bool, dataDeletionScheduled: Bool? = false, dataExportRequestedAt: Date? = nil) {
        self.levelTestCompleted = levelTestCompleted
        self.tutorialCompleted = tutorialCompleted
        self.personalizationReady = personalizationReady
        self.dataDeletionScheduled = dataDeletionScheduled
        self.dataExportRequestedAt = dataExportRequestedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case levelTestCompleted
        case tutorialCompleted
        case personalizationReady
        case dataDeletionScheduled
        case dataExportRequestedAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(levelTestCompleted, forKey: .levelTestCompleted)
        try container.encode(tutorialCompleted, forKey: .tutorialCompleted)
        try container.encode(personalizationReady, forKey: .personalizationReady)
        try container.encodeIfPresent(dataDeletionScheduled, forKey: .dataDeletionScheduled)
        try container.encodeIfPresent(dataExportRequestedAt, forKey: .dataExportRequestedAt)
    }
}

